Home works
VolkovaKaterina/New_HW pull request #1
Opened 2022-01-20 11:20 UTC by VolkovaKaterina

2022-01-21 15:41 UTC, oleh-rovenskyi-nortal requested changes

2022-01-21 15:41 UTC, oleh-rovenskyi-nortal commented on recursion/index.html
> +<script src="script.js"></script>
You should use script with the attribute `defer`.  PLease read about deffer and async.

2022-01-21 15:41 UTC, oleh-rovenskyi-nortal commented on recursion/script.js
> +        return a===b? a:`${a} ${allNumbers(a-1,b)}`
Need to format code. Wrong code style.

2022-01-21 15:41 UTC, oleh-rovenskyi-nortal commented on recursion/script.js
> +        return a===b? a:`${a} ${allNumbers(a+1,b)}`
Need to format code. Wrong code style.

2022-01-21 15:41 UTC, oleh-rovenskyi-nortal commented on recursion/script.js
> +// Напишите функцию которая принимает два числа A и В.
Code style.

2022-01-21 15:41 UTC, oleh-rovenskyi-nortal commented on recursion/script.js
> +    console.log(`${hours}:${minutes}:${seconds}`)
Need to remove console.log. The final code should be without console.log

2022-01-21 15:41 UTC, oleh-rovenskyi-nortal commented on recursion/script.js
> +    clock();
You should not call a second time `clock`, you have an interval. better to change time interval.

2022-01-21 15:41 UTC, oleh-rovenskyi-nortal commented on recursion/script.js
> +  (isFullTime)? div.innerHTML = `${hours}:${minutes}:${seconds}`: div.innerHTML = `${hours}:${minutes}`
Redundant  div.innerHTML. You should use one  div.innerHTML.

2022-01-21 15:41 UTC, oleh-rovenskyi-nortal commented on closure/index.html
> +<script src="script.js"></script>
Please read about deffer and async. Need to use defer.

2022-01-21 15:41 UTC, oleh-rovenskyi-nortal commented on closure/script.js
> +function sum(x) {// ваш код}
Code style

2022-01-21 15:41 UTC, oleh-rovenskyi-nortal commented on OOP/index.html
> +<script src="script.js"></script>
Need to use defer.

2022-01-21 15:41 UTC, oleh-rovenskyi-nortal commented on OOP/script.js
> +clock.addEventListener('click', ev => {
You should implement change format inside class.

2022-01-21 15:41 UTC, oleh-rovenskyi-nortal commented on OOP/script.js
> +    isFullTime ? short.render() : full.render()
You should change the format instead of changing the instance of render.

2022-01-21 15:41 UTC, oleh-rovenskyi-nortal commented on OOP/script.js
> +    isFullTime ? full.render() : short.render();
Update current logic according to comments above.

2022-01-21 15:41 UTC, oleh-rovenskyi-nortal commented on promise/index.html
> +<script src="script.js"></script>
Need to use defer.

2022-01-21 15:41 UTC, oleh-rovenskyi-nortal commented on promise/script.js
> +// delay(1000).then(() => console.log("Hello!"))
Code style.

2022-01-21 15:41 UTC, oleh-rovenskyi-nortal commented on async await/index.html
> +<script src="script.js"></script>
Need to use defer.

2022-01-21 15:41 UTC, oleh-rovenskyi-nortal commented on async await/script.js
> +        let user = await getUserInfo();
You shouldn't redeclare the variable.

2022-01-21 15:41 UTC, oleh-rovenskyi-nortal commented on async await/script.js
> +(async () => {
Redundant logic. You can call just getResult();

2022-01-21 15:41 UTC, oleh-rovenskyi-nortal commented on async await/script.js
> +(async () => {
Redundant logic. You can call just getInfo();

2022-01-23 17:17 UTC, VolkovaKaterina commented on async await/script.js
> +        let user = await getUserInfo();
I didn't quite catch where the variable is redeclared

2022-01-24 08:52 UTC, oleh-rovenskyi-nortal commented on OOP/script.js
> +    start() {
You all should have a stop method.

2022-01-24 16:47 UTC, oleh-rovenskyi-nortal requested changes

2022-01-24 16:47 UTC, oleh-rovenskyi-nortal commented on OOP/script.js
> +        this.button.addEventListener('click', () => {
Либо переменную нужно переименовать, которая отвечает за то по какой кнопке нажали или проверять через target (css класс или html attr) на элементе.

2022-01-24 16:47 UTC, oleh-rovenskyi-nortal commented on OOP/script.js
> +            this.isFullformat = !this.isFullformat
Есть переменная по которой можно определить какой формат времени нужно отображать, но она не используется в методе рендер.

2022-01-24 16:47 UTC, oleh-rovenskyi-nortal commented on OOP/script.js
> +            !this.isFullformat ? this.render() : new FullFormat(this.elem, this.button).render();
У тебяя класс ShortFormat не должен что либо знать о FullFormat, не нужно FullFormat использовать внутри ShortFormat. Нужно просто менять формат отображения.

2022-01-24 16:47 UTC, oleh-rovenskyi-nortal commented on OOP/script.js
> +            this.isFullformat ? this.render() : new ShortFormat(this.elem, this.button).render();
Посмотри комментарии к ShortFormat

2022-01-25 19:02 UTC, oleh-rovenskyi-nortal commented on promise/script.js
> +        response => {
Данную конструкцию можно упростить 
.then((response) => getUserAvatar(response))

2022-01-25 19:02 UTC, oleh-rovenskyi-nortal approved these changes

2022-01-28 15:59 UTC, merged